function SetColourScheme()
    let cs = "deus"
    let b16_theme_file = $HOME . "/.local/share/b16_theme/current_theme"
    if filereadable(b16_theme_file)
        let cs = readfile(b16_theme_file)[0]
    endif
    execute "colorscheme" cs
endfunction

call SetColourScheme()

" Show line numbers
set number

" Show rulers
set colorcolumn=80,100
set cuc
set cul

" Search settings
set hlsearch
set ignorecase
set incsearch

" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

" Tab settings
set expandtab
set tabstop=4
set shiftwidth=0    " use same value as tabstop
set softtabstop=-1  " ditto
set autoindent

" Remove trailing whitespace on save
autocmd BufWritePre * :%s/ \+$//e
"
" Spell check
autocmd BufRead     * setlocal spell spelllang=en_gb

" Custom mappings

" Scroll window with jk
noremap <C-j> <C-e>
noremap <C-k> <C-y>

" Make Y behave like C, D
noremap Y y$

" I don't see the point in selecting the newline with '$'... make it behave
" like 'g_' instead
noremap $ g_

" Add a new line above/below
map [<Space> O<Esc>j
map ]<Space> o<Esc>k

" Move selection to previous line as a new variable
function! CreateVariable()
    let var_name = input("new variable name: ")
    exe 'normal gv"jc' . var_name

    if &filetype == "python"
        exe 'normal O' . var_name . ' = '
        normal "jp
    elseif &filetype == "sh"
        exe 'normal O' . var_name . '="'
        normal "jpA"
    elseif &filetype == "javascript"
        exe 'normal Olet ' . var_name . ' = '
        normal "jpA;
    elseif &filetype == "erlang"
        exe 'normal O' . var_name . ' = '
        normal "jpA,
    else
        " Note: same as python for now
        exe 'normal O' . var_name . ' = '
        normal "jp
    endif
endfunction

vnoremap A :call CreateVariable()<CR>

" Operator to select whole line
onoremap il :norm ^vg_<cr>

" Search for selection
vnoremap q "jy/<C-r>j<CR>N
" Search for selection and start editing (repeat with n and .)
vmap Q qcgn

" Typo avoidance
noremap :W :w
noremap :Q :q
noremap :BD :bd

" Don't have spaces inside brackes when using surround plugin
let g:surround_40 = "(\r)"
let g:surround_91 = "[\r]"
let g:surround_123 = "{\r}"

" No point showing whitespace changes in gutter as it makes
" it hard to see actual changes
let g:gitgutter_diff_args = "-w"

" updatetime is used by GitGutter plugin: make short so that it
" is more responsive
set updatetime=200

" Functions

" Settings useful for writing plain text files
function WriteText()
    set textwidth=79
    set colorcolumn=80
    set nocul
    set formatoptions+=n

    if &filetype == "tex" || &filetype == "plaintex"
        let &formatlistpat = "^\\s*.item\\s"
    else
        let &formatlistpat = "^\\s*[\\-\\*#]\\.\\?\\s"
    endif
endfunction

" Function to create a new tab, lcd to somewhere, and rename the tab (using
" taboo.vim)
function! NewTabFunction(path)
    tabnew
    exe "lcd " .  a:path
    " get tab name as follows:  convert to full path, remove trailing slash,
    " and  get last component
    let name = fnamemodify(a:path, ":p:s?/$??:t")
    exe "TabooRename " . name
endfunction

command! -nargs=1 -complete=file Nt call NewTabFunction("<args>")

" Underline a line
function! Underline()
    let length = col("$") - 1
    let char = nr2char(getchar())
    normal o
    exe "normal " . length . "I" . char
endfunction

function! LogEntry()
    exe "norm ] j"
    read !date '+\%d-\%m-\%Y'
    norm yypv$r-
endfunction

function! StartEndLog()
    let line = getline(".")
    let time = substitute(system("date '+\%H:\%M'"), "\\n", "", "")
    if line =~ "^\- \\d\\d:\\d\\d - \?:.*"
        exe "normal 0f?cl" . time
    else
        exe "normal o- " . time . " - ?:"
    endif
endfunction

" Leader mappings

noremap <Leader>f gwap
noremap <Leader>l :call StartEndLog()<CR>
noremap <Leader>s :call SetColourScheme()<CR>
noremap <Leader>u :call Underline()<CR>
" Strikethough a like
noremap <Leader>x :s/./&̶/g<CR>:noh<CR>
