theme = "base16-materia"

[editor]
rulers = [79, 99]
scrolloff = 0
auto-pairs = false

[editor.cursor-shape]
normal = "block"
insert = "bar" 
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-p = "file_picker"
C-x = "buffer_picker"
C-l = "symbol_picker"
C-k = "scroll_up"
C-j = "scroll_down"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
